baseURL = "https://orangehealth.nl/"
languageCode = "en-us"
title = "Orange Health"
theme = "hugo-arcana"
copyright = "© ACTA. All rights reserved"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
  [caches.misc]
    dir = ':cacheDir/downloads'

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.nl]
        languageName = "Nederlands"
        weight = 2

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = true

[markup.goldmark.renderer]
unsafe = true


#    [[params.social]]
#        title = "Twitter"
#        icon = "fa-twitter"
#        url = "#"
#    [[params.social]]
#        title = "Facebook"
#        icon = "fa-facebook-f"
#        url = "#"
#    [[params.social]]
#        title = "GitHub"
#        icon = "fa-github"
#        url = "#"
#    [[params.social]]
#        title = "LinkedIn"
#        icon = "fa-linkedin-in"
#        url = "#"
#    [[params.social]]
#        title = "Creative Commons"
#        icon = "fa-creative-commons"
#        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Health Holland"
        [[params.footer.links.links]]
            title = "Health~Holland"
            url = "https://www.health-holland.com/"
        [[params.footer.links.links]]
            title = "Health~Holland Newsletter"
            url = "https://www.lsh-update.com/mkb"
         [[params.footer.links.links]]
             title = "Health~Holland Programs"
             url = "https://www.health-holland.com/programs"
#        [[params.footer.links.links]]
#            title = "Rutrum accumsan dolor"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Mattis rutrum accumsan"
#            url = "#"
#       [[params.footer.links.links]]
#            title = "Suspendisse varius nibh"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Sed et dapibus mattis"
#            url = "#"
        [[params.footer.links]]
            header = "Downloads"
        [[params.footer.links.links]]
            title = "Calltekst 2026 ORANGEHealth PPS"
            url = "/downloads/Calltekst2026ORANGEHealthPPS.docx"
        [[params.footer.links.links]]
             title = "preproposal ORANGEHealth PPS Call 2026"
             url = "/downloads/preproposalORANGEHealthPPSCall2026.docx"
         [[params.footer.links.links]]
              title = "Bijlagen bij aanvraagformulier"
              url = "/downloads/Appendices application form_Programma.pdf"
         [[params.footer.links.links]]
              title = "Template Letter of Commitment 2026 – Nederlands"
              url = "/downloads/Template-letter-of-commitment_2026-Nederlands_PPS subsidie_Programma.docx"
         [[params.footer.links.links]]
              title = "Template Letter of Commitment 2026 – Engels"
              url = "/downloads/Template-letter-of-commitment_2026-English_PPP Subsidy_Program.docx"
         [[params.footer.links.links]]
              title = "Budgetformulier projecten 2026"
              url = "/downloads/TKI-LSH Standaard Budget Form - 2026.xlsx"
         [[params.footer.links.links]]
              title = "Projectprofiel 2026"
              url = "/downloads/Project profile TKI-LSH_PPP subsidy_2026.docx"
         [[params.footer.links.links]]
              title = "Datamanagementplan 2026"
              url = "/downloads/TKI-LSH Datamanagementplan Formulier - PPS subsidie_Programma.docx"
         [[params.footer.links.links]]
              title = "Consortium Agreement Template – Programs - Standard"
              url = "/downloads/Consortium AgreementPPPProgramma-STANDARD.docx"
         [[params.footer.links.links]]
              title = "Consortium Agreement Template – Programs – Clinical Studies"
              url = "/downloads/Consortium AgreementPPPProgramma-CLINICALSTUDIES.docx"
#        [[params.footer.links.links]]
#            title = "Duis neque nisi sed"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Sed et dapibus quis"
#            url = "#"
#        [[params.footer.links.links]]
#            title = "Rutrum amet varius"
#            url = "#"

#         [params.footer.contact_form]
#             enabled = true
#             header = "Get In Touch"
#             action = "mailto:c.kleverlaan@acta.nl"
