[[main]]
    name = "ORANGEFORCE"
    weight = 30
    pageRef = 'ORANGEFORCE-general'
[[main]]
    parent = "ORANGEFORCE"
    name = "Mondzorg voor Oudere"
    weight = 31
    pageRef = 'WP1'
[[main]]
    parent = "ORANGEFORCE"
    name = "Mondzorg data"
    weight = 32
    pageRef = 'WP2'
[[main]]
    parent = "ORANGEFORCE"
    name = "Meten in de Mond"
    weight = 33
    pageRef = 'WP3'
[[main]]
    name = "Oral Cohorts"
    weight = 70
    pageRef = 'OralCohort-general'
[[main]]
    parent = "Oral Cohorts"
    name = "GLOBE"
    weight = 71
    pageRef = 'Cohort_GLOBE'
[[main]]
    parent = "Oral Cohorts"
    name = "LASA"
    weight = 72
    pageRef = 'Cohort_LASA'
[[main]]
    parent = "Oral Cohorts"
    name = "Lifelines"
    weight = 73
    pageRef = 'Cohort_Lifelines'
[[main]]
    parent = "Oral Cohorts"
    name = "RODAM"
    weight = 74
    pageRef = 'Cohort_RODAM'
[[main]]
    parent = "Oral Cohorts"
    name = "Maastricht Study"
    weight = 75
    pageRef = 'Cohort_TheMaastrichtStudy'

